### ISSUE TITLE
The guava version is not compatible with spring-data-cassandra library

### ISSUE THREAD

**Issue by JCL38-ORANGE** [jsevellec/cassandra-unit#248]
Hello,

The last cassandra-unit release brings an upgrade to a most recent guava release.
...
             <groupId>com.google.guava</groupId>
             <artifactId>guava</artifactId>
             <version>21.0</version>
...
This guava version is not compliant with the old cassandra datastax driver which is still included in the stable spring-data-cassandra framework (1.5.7).
https://jira.spring.io/browse/DATACASS-424
https://github.com/spring-projects/spring-boot/issues/8809

I need to downgrade the guava version to 18.0 in order to use both cassandra-unit and spring-data-cassandra.
...
             <groupId>com.google.guava</groupId>
             <artifactId>guava</artifactId>
             <version>18.0</version>
...
Regards,
Jean-Christophe.

**Comment by NYPD** [comment]
I guess this is something the user will have to exclude in the pom.xml.

**Comment by asarkar** [comment]
The [cassandra-all](https://search.maven.org/artifact/org.apache.cassandra/cassandra-all/3.11.4/jar) library references classes that have been removed from Guava, for example `com.google.common.base.CharMatcher.DIGIT`. This causes runtime errors like 
```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.io.sstable.format.SSTableFormat$Type
```

**Comment by t2y** [comment]
In my environment, I could build using guava 25.1 without an error. But, the error occurred using guava 26.0.

```gradle
implementation 'com.datastax.oss:java-driver-core:4.3.1'                      
testImplementation 'org.cassandraunit:cassandra-unit:4.3.1.0'                      
```

```bash
$ gradle --version
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------
Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.6 (Ubuntu 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OS:           Linux 5.3.0-28-generic amd64
```

**Comment by erwanJarno** [comment]
// https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html
    testImplementation("org.cassandraunit:cassandra-unit-spring:4.3.1.0") {
        testImplementation("com.google.guava:guava") {
            version {
                // https://github.com/jsevellec/cassandra-unit/issues/248
                // https://issues.apache.org/jira/browse/CASSANDRA-15245
                strictly("18.0")
            }
        }
    }

**Comment by nebulorum** [comment]
Plus one to this issue but with Java 30.1-jre.

**Comment by asarkar** [comment]
This issue been open for almost 4 years, and the only workaround offered is to use an ancient Guava version? There's also another long standing ticket for supporting Java 11, which has been around for 3 years. The general vibe I get from using the cassandra-unit library is "we have created a library, thanks, $^% you very much".

**Comment by jsevellec** [comment]
**Cause.** cassandra-unit pinned guava 18, which clashed with what spring-data-cassandra needed.

**Fixed in #345.** guava is now 32.0.1-jre, managed by Cassandra's own dependency set (85e4dae), and the shaded artifact that made clashes worse is gone.

Fixed on `main` and shipping in **5.0.0**, which is not on Maven Central yet — Central still has 4.3.1.0. Docs: https://github.com/jsevellec/cassandra-unit/tree/main/docs

Closing as fixed; sorry this took so long.
