### ISSUE TITLE
DataLoader doesn't work in 1.0.1.1

### ISSUE THREAD

**Issue by tomvandenberge** [jsevellec/cassandra-unit#2]
Hi,
I'm using cassandra-unit 1.0.1.1, and I'm getting a nasty exception when executing the code from the xml example:

EmbeddedCassandraServerHelper.startEmbeddedCassandra();
DataLoader dataLoader = new DataLoader("TestCluster", "localhost:9171");
dataLoader.load(new ClassPathXmlDataSet("simpleDataSet.xml"));

2011-11-05 13:53:37,897 [pool-2-thread-2] ERROR cassandra.thrift.Cassandra$Processor - Internal error processing system_add_keyspace
java.lang.NoSuchMethodError: org.apache.cassandra.thrift.CfDef.isSetRow_cache_keys_to_save()Z
    at org.apache.cassandra.config.CFMetaData.applyImplicitDefaults(CFMetaData.java:619)
    at org.apache.cassandra.config.CFMetaData.fromThrift(CFMetaData.java:637)
    at org.apache.cassandra.thrift.CassandraServer.system_add_keyspace(CassandraServer.java:964)
    at org.apache.cassandra.thrift.Cassandra$Processor$system_add_keyspace.process(Cassandra.java:3912)
    at org.apache.cassandra.thrift.Cassandra$Processor.process(Cassandra.java:2889)
    at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:187)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)

When I switch back to 0.8.0.2.3, it works fine. I'm relying on maven to resolve all dependencies.

Any help would be greatly appreciated.
Tom
