### ISSUE TITLE
NoSuchMethodError: org.apache.cassandra.utils.FBUtilities.toWriteUTFBytes

### ISSUE THREAD

**Issue by ogg1e** [jsevellec/cassandra-unit#151]
For some reason, when I upgraded to the latest (2.2.2-SNAPSHOT) I now get this at startup of my tests. I'm using the same dependencies that is in the pom. 2.1.8 for cassandra-driver and 2.2.2 for cassandra-all

It used to work with 2.1.9.2 and the older cassandra driver.
`
Nov 19, 2015 10:06:22.564/AST [pool-1-thread-1] [exitOrFail] ERROR Exception encountered during startup
java.lang.NoSuchMethodError: org.apache.cassandra.utils.FBUtilities.toWriteUTFBytes(Ljava/lang/String;)[B
	at org.apache.cassandra.config.CFMetaData.<init>(CFMetaData.java:265)
	at org.apache.cassandra.config.CFMetaData.newSystemMetadata(CFMetaData.java:324)
	at org.apache.cassandra.config.CFMetaData.compile(CFMetaData.java:306)
	at org.apache.cassandra.db.SystemKeyspace.compile(SystemKeyspace.java:257)
	at org.apache.cassandra.db.SystemKeyspace.<clinit>(SystemKeyspace.java:96)
	at org.apache.cassandra.config.Schema.<init>(Schema.java:90)
	at org.apache.cassandra.config.Schema.<clinit>(Schema.java:49)
	at org.apache.cassandra.service.StartupChecks$8.execute(StartupChecks.java:275)
	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:103)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:162)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:511)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by ogg1e** [comment]
I think I've figured out the issue. I'm in dependency hell. 
We use spark as well, and use spark-cassandra-connector version 1.4.0, which depends on cassandra-clientutil 2.1.5 

That dependency has a different version of the FBUtilities class.
uggh

**Comment by ogg1e** [comment]
@chaochao I can't recall the exact fix, but I think I had to add some exclusions to the pom file for cassandra-unit dependency with a scope of test:
``
 <exclusion>
                    <artifactId>cassandra-all</artifactId>
                    <groupId>org.apache.cassandra</groupId>
                </exclusion>
                <exclusion>
                    <groupId>com.datastax.cassandra</groupId>
                    <artifactId>cassandra-driver-core</artifactId>
                </exclusion>
``
I also had to make sure I had the correct cassandra dependencies for cassandra-all and spring-data-cassandra.

**Comment by MALPI** [comment]
Can be closed since it's not an cassandra-Unit issue
